export default [
  { name: "Export", desc: "出口，输出" },
  { name: "Default", desc: "默认结果，缺省值" },
  { name: "achieve", desc: "达到，取得，实现；获得成功" },
  { name: "basics", desc: "基本因素（或原理、原则、规律等）；基本设施；基本需要" },
  { name: "rack", desc: "架子；支架；机架；齿条；行李架" },
  { name: "Methods", desc: "方式、方法；method复数" },
  { name: "Active", desc: "积极，主动" },
  { name: "Grid", desc: "网格，css的Grid布局" },
  { name: "Refresh", desc: "刷新" },
  { name: "Opacity", desc: "透明度" },
  { name: "Scale", desc: "缩放" },
  { name: "Spirit", desc: "精神、精灵" },
  { name: "Micro", desc: "微小的、极小" },
  { name: "Soft", desc: "软的、柔软" },
  { name: "Container", desc: "容器、集装器" },
  { name: "Instance", desc: "实例" },
  { name: "Progress", desc: "进度" },
  { name: "Drawer", desc: "抽屉" },
  { name: "Recorder", desc: "录音机" },
  { name: "Insert", desc: '插入' },
  { name: "Install", desc: '安装' },
  { name: 'Lock', desc: '锁' },
  { name: 'Expire', desc: '某物的有效期结束或失效' },
  { name: 'Protocol', desc: '协议' },
  { name: 'Params', desc: '参数' },
  { name: 'Development', desc: '开发，研发'},
  { name: 'Production', desc: '生产' },
  { name: 'Example', desc: '示例' },
  { name: 'Local', desc: '当地，本地' },
  { name: 'Storage', desc: '储存' },
  { name: 'Position', desc: '位置' },
  { name: 'Absolute', desc: '绝对，绝对值' },
  { name: 'Relative', desc: '相对' },
  { name: 'Static', desc: '静态' },
  { name: 'Sticky', desc: '粘性的'},
  { name: 'State', desc: '状态，用于描述系统或程序的当前状况' },
  { name: 'Status', desc: '状态，用于描述某个特定操作、请求或事件的结果或状态' },
  { name: 'Router', desc: '路由器，网络设备' },
  { name: 'Route', desc: '路由，路线，航线，网络传输路径' },
  { name: 'Memory', desc: '内存' },
  { name: 'Disk', desc: '磁盘' },
  { name: 'Cache', desc: '缓存，高速缓存存储器' },
  { name: 'Session', desc: '会期，会话' },
  { name: 'Heap', desc: '堆，是一种特殊的完全二叉树结构' },
  { name: 'Stack', desc: '栈，LIFO: Last In First Out'},
  { name: 'Extend', desc: '扩展' },
  { name: 'Array', desc: '数组' },
  { name: 'Buffer', desc: '缓冲区' },
  { name: 'Scope', desc: '范围' },
  { name: 'Symbol', desc: '象征，符号，标志' }

];
